version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: vaccination_postgres
    environment:
      POSTGRES_DB: vaccination_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d vaccination_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  vaccination-api:
    container_name: vaccination_api_app
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/vaccination_db 
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update 
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres_data: